<a href="https://colab.research.google.com/github/Sukhi24397/Pract0/blob/main/Experiment9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Sukhi N
#25070123112
#Study of Numpy library

In [1]:
#Declaration of Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3] , [4,5,6]])
print(a)
print(b)
display(a.dtype)
print(b * 2)
print(a + 5)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


dtype('int64')

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [2]:
#Dimension of Arrya
print(a.ndim)
print(b.ndim)

1
2


In [3]:
print(a.shape)
print(b.shape)


(7,)
(2, 3)


In [4]:
print(a.dtype)

int64


In [5]:
# In-Built functions using Numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [9]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [10]:
np.mean(a)

np.float64(93.0)

In [11]:
np.median(a)

np.float64(30.0)

In [12]:
np.max(a)

np.int64(500)

In [13]:
np.min(a)

np.int64(1)

In [14]:
np.sum(a)

np.int64(651)

In [15]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

det = np.linalg.det(a)
print(det)

transpose = np.transpose(a)
print(transpose)

0.0
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[7,8,9],[4,6,5],[3,2,1]])

print(np.dot(a,b))


[[ 24  26  22]
 [ 66  74  67]
 [108 122 112]]
